version: "3"

services:
    psql:
        container_name: edr_psql
        build: ./psql
        ports:
                - 5432:5432
        networks:
                - edr_network
        environment:
                - POSTGRES_DB=edr
                - POSTGRES_USER=capstone
                - POSTGRES_PASSWORD=capstone

    core:
        container_name: edr_core
        build: ./core
        ports:
           - 5000:5000
        depends_on:
                - "psql"
        networks:
                - edr_network
        links:
                - psql
                - elastic
        environment:
                - DB_HOST=psql
                - DB_PORT=5432
                - DB_USER=capstone
                - DB_PASS=capstone
                - DB_NAME=edr
                - ES_HOST=elastic

    elastic:
        container_name: edr_elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        ports:
                - 9200:9200
        networks:
                - edr_network
        links:
                - psql
        volumes:
                - data01:/usr/share/elasticsearch/data
        environment:
                - discovery.type=single-node
                - network.host=0.0.0.0

    kibana:
        image: docker.elastic.co/kibana/kibana:7.6.2
        container_name: edr_kibana
        links:
                - elastic
        ports:
                - 5601:5601
        networks:
                - edr_network
        environment:
                - ELASTICSEARCH_HOSTS=http://elastic:9200
                - ELASTICSEARCH_URL=http://elastic:9200

networks:
    edr_network:
        driver: bridge

volumes:
    data01:
        driver: local
