version: "3"

services:
    psql:
        container_name: edr_psql
        build: ./psql
        ports:
                - 5432:5432
        network_mode: bridge
        environment:
                - POSTGRES_DB=edr
                - POSTGRES_USER=capstone
                - POSTGRES_PASSWORD=capstone
    core:
        container_name: edr_core
        build: ./core
        ports:
           - 5000:5000
        depends_on:
                - "psql"
        network_mode: bridge
        links:
                - psql
        external_links:
                - cranky_shaw:elastic
        environment:
                - DB_HOST=psql
                - DB_PORT=5432
                - DB_USER=capstone
                - DB_PASS=capstone
                - DB_NAME=edr
                - ES_HOST=elastic
